name: Android Build

on:
  pull_request:
  push:
  workflow_dispatch:




jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      # Checkout Upload Apk
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Apk
          path: app/build/outputs/apk/debug/app-debug.apk